[project]
name = "MochaMingle"
authors = []
description = ""
telemetry = false
requirements = []
[contracts.mocha-token]
path = "contracts/mocha-token.clar"
depends_on = []

[contracts.recipe-manager]
path = "contracts/recipe-manager.clar"
depends_on = []

[contracts.user-profiles]
path = "contracts/user-profiles.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
